---
- name: Add key into repo
  shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | apt-key add -

- name: Insert address of repo into source.list
  shell: echo deb http://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list

- name: Update apt
  apt: update_cache=yes

- name: Install jenkins
  apt: pkg=jenkins

- name: Check jenkins status
  shell: systemctl status jenkins
  notify: start jenkins