---

- name: Add key into repo
  shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

- name: Insert address of repo into source.list
  shell: echo deb https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list

- name: Update apt
  apt: update_cache=yes

- name: Install jenkins
  apt: pkg=jenkins

- name: Check jenkins status
  shell: systemctl status jenkins
  register: jenkins_status
  ignore_errors: True

- name: Start jenkins
  when: jenkins_status|success
  shell: systemctl start jenkins
