---
- name: Add ppa repository for java
  apt_repository: repo=ppa:{{ java.ppa }}

- name: Update apt
  apt: update_cache=yes

- name: Accept license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

- name: See license
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: Install java
  apt: pkg=oracle-java8-installer state=latest